# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'text-validator-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for text-validator-demo
  pod 'R.swift'
  pod 'IQKeyboardManager'
  pod 'Kingfisher'

end
